[package]
name = "tim"
version = "0.2.0"
edition = "2021"
description = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.3.18"
fltk-theme = "0.6.0"
rodio = "0.16.0"

[package.metadata.bundle]
name = "Tim"
identifier = "com.ddno.tim"
icon = ["assets/timer.png"]
resources = ["assets/*.wav", "assets/*.mp3"]
category = "Utility"
